select * from employees;
select last_name from employees;
select last_name,salary,salary+1000 from employees;
select first_name||' '||last_name from employees;
select 'The employee Id of ' ||first_name||' '||last_name||' '||'is '||employee_id as details,salary as wages from EMPLOYEES;
select 'The employee Id of ' ||first_name||' '||last_name||' '||'is '||employee_id as details,salary from EMPLOYEES;
select last_name,salary,salary+300 Updated_wages from EMPLOYEES;
select last_name,salary,salary*12+100,12*(salary+100) from EMPLOYEES;
select last_name, 12*salary*commission_pct from employees;
select last_name as name,commission_pct as commission from EMPLOYEES;
select last_name "Name",commission_pct as "Commission" from EMPLOYEES;
SELECT employee_id, job_id FROM employees UNION SELECT employee_id, job_id FROM job_history;
SELECT employee_id, job_id FROM employees UNION ALL SELECT employee_id, job_id FROM job_history;
SELECT employee_id, job_id FROM employees INTERSECT SELECT employee_id, job_id FROM job_history;
SELECT employee_id, job_id FROM employees MINUS SELECT employee_id, job_id FROM job_history;
SELECT location_id, department_name "Department",TO_CHAR(NULL) "Warehouse location" FROM departments UNION SELECT location_id,TO_CHAR(NULL) "Department", state_province FROM locations;
desc employees;
INSERT INTO departments (department_id, department_name, location_id) VALUES (&department_id, '&department_name',&location);
UPDATE employees SET job_id = (SELECT job_id FROM employees WHERE employee_id = 205), salary = (SELECT salary FROM employees WHERE employee_id = 205) WHERE employee_id=113;
select job_id from employees where employee_id=205;
SELECT employee_id, last_name, job_id, department_id FROM employees WHERE department_id = 90;
SELECT last_name FROM employees WHERE hire_date = '17-FEB-96';
SELECT last_name, salary FROM employees WHERE salary <= 3000;
SELECT last_name, salary FROM employees WHERE salary BETWEEN 2500 AND 3500;
SELECT employee_id, last_name, salary, manager_id FROM employees WHERE manager_id IN (100, 101, 201);
SELECT first_name FROM employees WHERE first_name LIKE 'S%';
SELECT last_name FROM employees WHERE last_name LIKE '_o%';
SELECT last_name, manager_id FROM employees WHERE manager_id IS NULL;
SELECT employee_id, last_name, job_id, salary FROM employees WHERE salary >= 10000 AND job_id LIKE '%MAN%';
SELECT employee_id, last_name, job_id, salary FROM employees WHERE salary >= 10000 AND job_id LIKE '%MAN%' AND last_name LIKE 'R%';
SELECT employee_id, last_name, job_id, salary FROM employees WHERE salary >= 10000 OR job_id LIKE '%MAN%';
SELECT last_name, job_id FROM employees WHERE job_id NOT IN ('IT_PROG', 'ST_CLERK', 'SA_REP');
SELECT last_name, job_id, salary FROM employees WHERE job_id = 'SA_REP' OR job_id = 'AD_PRES' AND salary > 15000;
SELECT last_name, job_id, salary FROM employees WHERE (job_id = 'SA_REP' OR job_id = 'AD_PRES') AND salary > 15000;
SELECT last_name, job_id, department_id, hire_date FROM employees ORDER BY hire_date DESC;
SELECT employee_id, last_name, salary*12 annsal FROM employees ORDER BY annsal;
SELECT employee_id, last_name, salary*12 FROM employees ORDER BY salary desc;
SELECT last_name, job_id, department_id, hire_date FROM employees ORDER BY 3;
SELECT last_name, department_id, salary FROM employees ORDER BY department_id, salary DESC;
SELECT employee_id, last_name, salary, department_id FROM employees WHERE employee_id = &employee_num;
SELECT last_name, department_id, salary*12 FROM employees WHERE job_id = '&job_title';
SELECT last_name, department_id, salary*12 FROM employees WHERE job_id = '&job_title' AND DEPARTMENT_ID = &department;
SELECT employee_id, last_name, job_id,&column_name FROM employees WHERE &condition ORDER BY &order_column;
DEFINE employee_num = 200 SELECT employee_id, last_name, salary, department_id FROM employees WHERE employee_id = &employee_num;